name: SFMobDrops
description: Add configurable Slimefun item drops to mobs on Minecraft 1.21.11 through 26.2 servers
version: ${project.version}
api-version: '1.21.11'
author: WalshyDev
main: dev.walshy.sfmobdrops.SfMobDrops
depend: [Slimefun]

commands:
  mobdrops:
    description: Manage and view Slimefun mob drops
    aliases: [sfmobdrops, mobdrop, sfmd]
    permission: sfmobdrops.admin

permissions:
  sfmobdrops.admin:
    description: Allows access to SFMobDrops administrative commands
    default: op
